name: booksgr
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.5.3

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  go_router: ^14.3.0
  provider: ^6.0.2
  dio: ^5.7.0
  image_picker: ^1.1.2
  build_runner: ^2.1.8
  json_serializable: ^6.8.0
  jwt_decode: ^0.3.1
  shared_preferences: ^2.3.2

dev_dependencies:
  flutter_test:
    sdk: flutteri
  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true
